import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SessionProvider } from 'next-auth/react';
import  Header  from "@/components/common/Header";
import BottomNav from "@/components/BottomNav";
import { createSupabaseBrowserClient } from '@/lib/supabaseClient';
import { SupabaseProvider } from '@/lib/supabaseContext';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) 

{
  const supabase = createSupabaseBrowserClient();

  return (
    <html lang="en">
      <body>
        <SupabaseProvider >
        <Header/>
        {children}
        <BottomNav/>
        </SupabaseProvider>
      </body>
    </html>
  );
}


